export const INSERT_COMMENT_REQUEST = 'INSERT_COMMENT_REQUEST'
export const INSERT_COMMENT_SUCCESS = 'INSERT_COMMENT_SUCCESS'
export const INSERT_COMMENT_FAILED = 'INSERT_COMMENT_FAILED'
//
export const FETCH_ALL_COMMENT_REQUEST = 'FETCH_ALL_COMMENT_REQUEST'
export const FETCH_ALL_COMMENT_SUCCESS = 'FETCH_ALL_COMMENT_SUCCESS'
export const FETCH_ALL_COMMENT_FAILED = 'FETCH_ALL_COMMENT_FAILED'
//
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED'