export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED'
//fetch all project
export const FETCH_ALL_PROJECT_REQUEST = 'FETCH_ALL_PROJECT_REQUEST'
export const FETCH_ALL_PROJECT_SUCCESS = 'FETCH_ALL_PROJECT_SUCCESS'
export const FETCH_ALL_PROJECT_FAILED = 'FETCH_ALL_PROJECT_FAILED'
// 
//assignUserProject
export const ASSIGN_USER_PROJECT_REQUEST = 'ASSIGN_USER_PROJECT_REQUEST'
export const ASSIGN_USER_PROJECT_SUCCESS = 'ASSIGN_USER_PROJECT_SUCCESS'
export const ASSIGN_USER_PROJECT_FAILED = 'ASSIGN_USER_PROJECT_FAILED'