export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED'
//
export const FETCH_DETAIL_TASK_REQUEST = 'FETCH_DETAIL_TASK_REQUEST'
export const FETCH_DETAIL_TASK_SUCCESS = 'FETCH_DETAIL_TASK_SUCCESS'
export const FETCH_DETAIL_TASK_FAILED = 'FETCH_DETAIL_TASK_FAILED'
//
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'